### ISSUE TITLE
Default type of 'ton'

### ISSUE THREAD

**Issue by Floppy** [spatchcock/quantify#9]
Quantify won't parse '2 tons'. Should it pick a default type of ton to use instead of failing? An option to do this, at least, would be good, to deal with fluffy human input.

**Comment by spatchcock** [comment]
Hey James,

The reason is that there are two types of imperial ton - US and UK. Both have symbols of 'ton', but their names and labels are differentiated as 'short ton'/ton_us and 'long ton'/ton_uk. 

So you can return these units on the basis of 'ton', 'short ton', 'long ton', 'ton_us' and 'ton_uk'. 'ton' is ambiguous between the two variants but it does return one as a priority - the UK variant since that one is initialized earlier. 

The reason for your exception is because - according to the gem - you are using what is defined as a unit symbol (ton) but pluralising it. Pluralization only works on the unit names, so Quantify would expect to see "2 short tons".

There are a few potential solutions:
1. Make pluralisation available to unit symbols - I don't think this is correct ("30 kg" means "thirty kilograms")
2. Choose one of the variants to be named 'ton' in the gem so that users automatically get 'tons' functioning out of the box - I (tentatively) don't think the gem should make this decision on behalf its users. I have no reason to favour one unit of the other, and the real world situation is that 'ton' is ambiguous without further clarification.
3. Reconfigure the descriptors of the units at runtime.

The latter choice basically means you override the unit configuration in your own context. This can be used generally to add, remove, rename, etc any and all of the units you want represented in you app. For the example at hand, stick this in an initialiser:

require 'quantify'

Quantify::Unit::NonSI.configure do

  # remove short ton
  Unit.ton_us.unload

  # Rename long ton
  Unit.ton_uk.configure_as_canonical do |unit|
    unit.name = 'ton'
  end

end

Then running Quantity.parse("25 tons") should return the correct quantity representation.

Cheers mate

Andrew
